version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    container_name: medusa_postgres
    environment:
      POSTGRES_USER: medusa_user
      POSTGRES_PASSWORD: medusa_pass
      POSTGRES_DB: medusa_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: medusa_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
